# Site settings
title: Blueforest
email: siweiran@gmail.com
description: > # 思伟的blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://siweiran.com" # the base hostname & protocol for your site
github_username:  blueforest
# Build settings

#markdown: kramdown
#kramdown:
# input: GFM
# syntax_highlighter: rouge

markdown: redcarpet
redcarpet :
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
